- hosts: "apt"
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: apt-update
      apt:
        update_cache: yes
        upgrade: 'yes'
- name: Notify discord
  hosts: "apt"
  vars:
    notify_discord_username: ansible
    notify_discord_webhook_id: '1392108384391790642'
    notify_discord_webhook_token: 'We-MVP1WQBN8MaNfUV91CEZixvEZu0AI0BxYWdz7kiU9tUTy43dk8y40TFziiyHIQP-7'
    notify_discord_webhook_id_regex: '^0|[1-9][0-9]*$'
    notify_discord_webhook_token_regex: '^[a-zA-Z0-9_-]+$'
    notify_discord_webhook_content: |-
      **Message from `{{ inventory_hostname }}` by *Ansible* ** :tada:
      Just a test, adjust it to your liking.

      You can use any Markdown formatting here [supported by Discord](
      https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline).
    notify_discord_send_from_host: localhost

  tasks:
    - name: Send Discord message
      community.general.discord:
        username: "{{ notify_discord_username }}"
        webhook_id: "{{ notify_discord_webhook_id }}"
        webhook_token: "{{ notify_discord_webhook_token }}"
        content: "{{ notify_discord_webhook_content }}"
      delegate_to: "{{ notify_discord_send_from_host }}"
      when:
        - notify_discord_webhook_id is match(notify_discord_webhook_id_regex)
        - notify_discord_webhook_token is match(notify_discord_webhook_token_regex)
        - notify_discord_webhook_content | length > 0
        - notify_discord_send_from_host is in (['localhost'] + groups['all'])
