- name: Push SSH key to all nodes
  hosts: all_servers
  gather_facts: no
  tasks:
    - name: Install authorized SSH key
      ansible.posix.authorized_key:
        user: jani
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
